### ISSUE TITLE
Restructure repository so it may house both plugins and Scriptfiles can be shared.

### ISSUE THREAD

**Issue by SargoDarya** [GusGold/DogeRedditHelper-Chrome#1]
If we want to create a Firefox Plugin too it might make sense to structure everything in a way that with a build script we could automate build processes as well as sharing code between the plugins. After all it doesn't make sense to write code twice.

**Comment by GusGold** [comment]
Probably not going to happen at the moment, especially with how basic it currently is.

I might reopen this in the future.
