### ISSUE TITLE
Identify transactions between self and other user

### ISSUE THREAD

**Issue by aortenzi** [GusGold/DogeRedditHelper-Chrome#6]
When trading with a user on dogemarket, it's very nice to know if you've had a previous transaction.  When highlighting a username, it would be wonderful to identify whether a) your username appears in any of their verification threads,  b) their username appears in any of your verification threads, or both.

**Comment by GusGold** [comment]
Ahh, that's a great idea. What info should be included, just how many times, and the volume?

e.g. You've done two trades with the user, one for 5000 and the other for 15000, the more info screen shows "Previous Trades: 2 Transactions for 20,000 Doge"?

**Comment by aortenzi** [comment]
I'm not sure.  More information is usually more valuable, but the nature of the verification threads make it hard to correlate two sides of the same transaction.  Maybe "User x claims two transactions with you for Ð100,000.  You claim three transactions with user x for Ð125,000." or similar.  You don't want it to appear like you've done business with someone else on his/her word alone.

Maybe it's as simple as flagging a notation in the highlight of the username, and having something appear next to a verification link to indicate that it links to you.  Highlighting your own username on a page also would help find the transaction within the verification comment.

**Comment by GusGold** [comment]
I reckon the information only needs to be based off your (the user's) verification threads. Because it doesn't matter if they are false or inaccurate because it's their fault (not someone elses). I think it should act as a guide rather than hard fact.

And yeah I usually love more info, but perhaps being concise would be better here?
